// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProEventos.API.Data;

namespace ProEventos.API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ProEventos.API.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagemURL")
                        .HasColumnType("TEXT");

                    b.Property<string>("Local")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lote")
                        .HasColumnType("TEXT");

                    b.Property<int>("QtdPessoas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tema")
                        .HasColumnType("TEXT");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            DataEvento = new DateTime(2026, 2, 19, 18, 46, 23, 868, DateTimeKind.Local).AddTicks(2178),
                            ImagemURL = "foto1.png",
                            Local = "Rio de Janeiro",
                            Lote = "1o Lote",
                            QtdPessoas = 250,
                            Tema = "Angular 11 e .NET 5"
                        },
                        new
                        {
                            EventoId = 2,
                            DataEvento = new DateTime(2026, 2, 20, 18, 46, 23, 869, DateTimeKind.Local).AddTicks(7087),
                            ImagemURL = "foto2.png",
                            Local = "São Paulo",
                            Lote = "2o Lote",
                            QtdPessoas = 250,
                            Tema = "Angular 11 e .NET 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
